#!/bin/bash
mAnalyse=0
kat=0
fil=0
sLink=0
totKat=0
totFil=0
totSLink=0
total=0
katalog=*
program=$(basename $0)

teller(){
  totSLink=0
  totFil=0
  totKat=0
  total=0
  if [[ $sLink = 1 ]]; then

  for i in $katalog; do
    if [[ -L $i ]]; then
      mAnalyse=1
      totSLink=$(( totSLink + 1 ))
    fi
  done

  echo -e "Det er $totSLink symbolske linker i denne mappen\n"

  fi

  if [[ $kat = 1 ]]; then

  for i in $katalog; do
    if [[ -d $i ]]; then
      mAnalyse=1
      totKat=$(( totKat + 1 ))
    fi
  done

  echo -e "Det er $totKat kataloger i denne mappen\n"

  fi

  if [[ $fil = 1 ]]; then

  for i in $katalog; do
   if [[ -f $i ]]; then
      mAnalyse=1
      totFil=$(( totFil + 1 ))
   fi
  done

  echo -e "Det er $totFil filer i denne mappen\n"

  fi
}

tellerAlt(){
  totSLink=0
  totFil=0
  totKat=0
  total=0
  for i in $katalog; do
    if [[ -d $i ]]; then
      totKat=$(( totKat + 1 ))
    fi

    if [[ -f $i ]]; then
      totFil=$(( totFil + 1 ))
    fi

    if [[ -L $i ]]; then
      totSLink=$(( totSLink + 1))
    fi

    if [[ -e $i ]]; then
      total=$(( total + 1 ))
    fi
  done

  echo -e "\n$totFil filer, $totSLink symbolske linker, $totKat kataloger, totalt $total\n"

}


clear

if [[ -n $1 ]]; then


  until [[ -d $1 || $# = 0 ]]; do

    case $1 in
      -L )
        sLink=1
        ;;
      -d )
        kat=1
        ;;
      -f )
        fil=1
        ;;
      -h )
        clear
        echo -e "\nProgrammet brukes slik:\n
          $program [mappe] [option]...\n
          eks:
          $program mappe1 -f -L
          $program mappe1 -f mappe2 -L
          $program mappe1 -f mappe2 mappe3 -f -L\n
          Opsjoner:
          -f rapporterer antall filer
          -L rapporterer antall symbolske linker
          -d rapporterer antall kataloger
          -h gir «usage» og avslutter
        "
        exit
        ;;
      * )
        clear
        echo -e "\nOBS! Feil syntax. Sjekk ut -h for usage\n"
        exit
    esac

    shift

  done

  if [[ $# = 0 ]]; then
    teller
  fi

  until [[ $# = 0 ]]; do

    if [[ ! -d $1 ]]; then
      clear
      echo -e "\nOBS! Feil syntax. Sjekk ut -h for usage\n"
      exit
    else
      katalog=$1/*
    fi

    echo -e "\nAnalyse for mappen $(dirname "$katalog"):"

    if [[ $mAnalyse = 0 ]]; then
      tellerAlt
    else

    teller

    fi

    shift

  done

else

tellerAlt

fi

exit