#!/bin/bash

until [[ $tall =~ ^[1-9]$ ]]; do

  tall=$1

  clear
  if [[ -z $1 ]]; then
    read -p "Velg et tall mellom 1-9: " tall
  fi

  if [[ $tall =~ ^[1-9]$ ]]; then

    for (( i = 1; i <= tall; i++ )); do
      for (( f = 1; f <= i; f++ )); do
        echo -n $i
      done
      echo
    done

  else

    echo "OBS! Dette var ikke et alternativ."
    sleep 1

    until [[ $# = 0 ]]; do
      shift
    done

    continue

  fi

done